### ISSUE TITLE
Ricerca su albopop.it e reindirizzamenti

### ISSUE THREAD

**Issue by nelsonmau** [ondata/albopop-enhanced#5]
Benché per il server temo che non vi siano alternative a quello dataninja adesso, vi chiedo se non sia il caso di definire questo punto.

L'unica soluzione che vedo possibile è creare il terzo livello: http;//cerca.albopop.it

@gpirrotta @aborruso @jenkin e @pieroit: che ne dite?

**Comment by aborruso** [comment]
Io non credo di sapere mettere il server in piedi, ma sono disposto a pagare personalmente per un po' di tempo un macchina Amazon (o similari)

**Comment by nelsonmau** [comment]
credo che la questione server sia da discutere in ondata, lancerei thread lì.
non è meglio intanto definire la ricerca in modo da renderla immediatamente accessibile e disponibile?

**Comment by aborruso** [comment]
On 6 September 2016 at 10:22, Andrea Nelson Mauro notifications@github.com
wrote:

> non è meglio intanto definire la ricerca in modo da renderla
> immediatamente accessibile e disponibile?

Per me ok

---

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

---

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by nelsonmau** [comment]
bene @aborruso scusa il blackout.
Dunque farei così:
- @aborruso punta il terzo livello `http://cerca.albopop.it` sull'ip dataninja
- @jenkin aggiusta il dns affinché a quella chiamata risponda albopop enhanced
- al momento teniamo sottotraccia tutto

oki?

**Comment by jenkin** [comment]
@aborruso io lato mio ho fatto tutto, non appena inserirai nel DNS `cerca A 136.243.XXX.XXX` (l'ip del nostro server), si vedrà la pagina che ora è nel nostro sottodominio dev.

**Comment by aborruso** [comment]
@jenkin fatto. Sembra esserci una richiesta di di pwd da parte di apache http://cerca.albopop.it/

**Comment by nelsonmau** [comment]
@aborruso sì è colpa mia, vorrei per il momento tenere un po' filtrata la cosa in attesa di mettere tutto su un server ondata

**Comment by nelsonmau** [comment]
@jenkin pubblichi cmq login e password qui in questa issue? graz

**Comment by nelsonmau** [comment]
@jenkin pubblichi cmq login e password qui in questa issue? graz

**Comment by jenkin** [comment]
V'ho mandato una mail...
